### ISSUE TITLE
use simplewebrtc

### ISSUE THREAD

**Issue by Trakya20601** [osharper/SignalR4SimpleWebRtc#1]
Hello there. I have a question. In this code, I did not understand where SimpleWebTc changed.

var xyz = new simplewebrtc () {
connection: ??
url: ??
}

Can you help? I really need.

**Comment by osharper** [comment]
ok, I'll try to make some working stuff here over the weekend

**Comment by osharper** [comment]
you can reference to this place https://github.com/osharper/SignalR4SimpleWebRtc/blob/master/Scripts/demo.ts#L30 but I still have to put some effort to make a working demo

**Comment by Trakya20601** [comment]
OK. I follow you. could you make this progeny with a sample in asp.net format? I'm sure many people like me are investigating this, but can not find any examples of asp.net.
we will be very happy if you help us.

**Comment by osharper** [comment]
of course, it might be even easier if your employer will contact me directly via upwork and I will do this job for him :) https://www.upwork.com/o/profiles/users/_~01911c1df938329089/
